include conf/distro/poky.conf

DISTRO = "jr"
DISTRO_NAME = "jr (yocto based embedded linux)"
DISTRO_VERSION = "1.0.0"

MAINTAINER = "javadramezanzadeh@gmail.com"
TARGET_VENDOR = "-jr"

# opengpl, wayland and vulkan are added by POKY_DEFAULT_DISTRO_FEATURES variable.
# we only keep opengl(because of eglfs)
DISTRO_FEATURES:remove = "wayland vulkan"

# install examples for qtcharts
PACKAGECONFIG:append:pn-qtcharts = " examples"

# x11 is added by DISTRO_FEATURES_DEFAULT, we don't need it.
DISTRO_FEATURES:remove = "x11"
