FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SPLASH_IMAGES:rpi = "file://jrlogo.png;outsuffix=jrlogo"

TARGET_CFLAGS +=  "-DPSPLASH_IMG_FULLSCREEN=1 -DPSPLASH_DISABLE_PROGRESS_BAR -DPSPLASH_DISABLE_STARTUP_MSG"